# Generated by Django 4.1.7 on 2023-04-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
