# Generated by Django 4.1.7 on 2023-04-22 01:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
