# Generated by Django 4.1.7 on 2023-04-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='summary',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
