# Generated by Django 4.2 on 2023-05-06 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='like',
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
