# Generated by Django 4.2 on 2023-05-06 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_room_like_room_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='likes',
        ),
        migrations.AddField(
            model_name='room',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
